version: '3.8'

services:
  # KeystoneDB gRPC Server
  kstone-server:
    image: parkerdgabel/kstone-server:latest
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: kstone-server
    ports:
      - "50051:50051"  # gRPC
      - "9090:9090"    # Metrics
    volumes:
      - kstone-data:/data
    environment:
      - RUST_LOG=info
      - DB_PATH=/data/mydb.keystone
      - MAX_CONNECTIONS=1000
      - CONNECTION_TIMEOUT=60
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "kstone-server"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - kstone-net

  # Prometheus (optional - for metrics collection)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    networks:
      - kstone-net
    profiles:
      - monitoring

  # Grafana (optional - for visualization)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - kstone-net
    profiles:
      - monitoring

volumes:
  kstone-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  kstone-net:
    driver: bridge
